# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'development'
    values:
      - 'development'
      - 'production'

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  javaVersion: '1.8'
  mavenOptions: '-Xmx3072m'
  databaseUrl:
    development: 'jdbc:sqlserver://dev-db-server:1433;DatabaseName=DevDatabase'
    production: 'jdbc:sqlserver://prod-db-server:1433;DatabaseName=ProdDatabase'

jobs:
- ${{ if contains(parameters.environment, 'development') }}:
  - job: development
    steps:
    - script: echo running configs of development env

- ${{ if contains(parameters.configs, 'production') }}:
  - job: production
    steps:
    - script: echo running configs of development env