# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'development'
    values:
      - 'development'
      - 'production'

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: javaVersion
    value: '1.8'

  - name: mavenOptions
    value: '-Xmx3072m'

  - name: databaseUrl
    value: 
      development: 'jdbc:sqlserver://dev-db-server:1433;DatabaseName=DevDatabase'
      production: 'jdbc:sqlserver://prod-db-server:1433;DatabaseName=ProdDatabase'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '$(mavenOptions)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '$(javaVersion)'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: echo "Using database URL: $(databaseUrl)"
  displayName: 'Print Database URL'

- script: echo "Running development-specific step"
  displayName: 'Development Step'
  condition: eq(variables['environment'], 'development')

- script: echo "Running production-specific step"
  displayName: 'Production Step'
  condition: eq(variables['environment'], 'production')
