
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: environment
    displayName: 'Target Environment'
    type: string
    default: 'development'
    values:
      - 'development'
      - 'production'

trigger:
- main

pool:
  vmImage: ubuntu-latest


jobs:
- ${{ if contains(parameters.environment, 'development') }}:
  - job: development
    steps:
    - script: echo running configs of development env

- ${{ if contains(parameters.environment, 'production') }}:
  - job: production
    steps:
    - script: echo running configs of development env